### ISSUE TITLE
AudioRecorder.service.requestAuthorisation not working on iOS

### ISSUE THREAD

**Issue by dannycortesv** [distriqt/ANE-AudioRecorder#1]
##### Expected behaviour

Mic permission should work on iOS

##### Actual behaviour

On iOS 11.0.3 Asking permission doesn't works on iOS, the dialog is no been triggered.

##### Environment 

- AIR SDK version:  27
- Device OS:  iOS 11.0.3 
- Device version: iPhone 6
- Development IDE:  Flash Builder
- Development OS: Mac OS

**Comment by bjeld** [comment]
Did you remember to at this in your InfoAdditions?
<key>NSMicrophoneUsageDescription</key>
<string>This text will be displayed in the accept microphone alert dialog</string>

**Comment by marchbold** [comment]
@bjeld is right, you must make sure you have that usage description text on iOS 10 + . 

What is `AudioRecorder.service.authorisationStatus()` returning? The dialog will only appear if this is "not determined". You only get one change to request the permission on iOS and once asked the dialog won't appear. You can only reset this by reseting all your device location and privacy settings, in the Settings app.

**Comment by dannycortesv** [comment]
Whatnks @bjeld  and @marchbold, i was missing the InfoAddition item, i just added it, also deleted / reinstalled the app, the first time i open it i got this status: unknown, but no Dialog is prompted, is possible that iOS 11 works different?

**Comment by marchbold** [comment]
Are you getting the dialog on iOS 10?

**Comment by dannycortesv** [comment]
Sorry currently i don’t have an iOS 10 device to test.

**Comment by marchbold** [comment]
Apologies, I've just been informed the iOS implementation is still in development. Currently this ANE only supports Android.

**Comment by dannycortesv** [comment]
Oh it's ok, any plans in to finish the iOS version?

**Comment by marchbold** [comment]
Yes, it's in active development, we were hoping for an update this month, but it's been moved to mid November now. Let me know if you need something urgently.

**Comment by dannycortesv** [comment]
I have no rush mid November is ok, thank you @marchbold, your help is great!

**Comment by marchbold** [comment]
Thanks for your patience!

**Comment by marchbold** [comment]
Hi, I've just checked in the first version of the iOS implementation. 

We have been able to successfully implement recording however the formats that iOS use don't seem to be playable by AIR using the NetStream method we were using for Android. 

They are however playable using the [MediaPlayer ANE](https://airnativeextensions.com/extension/com.distriqt.MediaPlayer) (which uses the native audio player). 

If anyone has any experience in issues with iOS playback of AAC/M4A we'd be happy for your input here.

**Comment by dannycortesv** [comment]
Thank you @marchbold, i'm going to start to play with this, my app is for both iOS and Android, what happen if a user records an audio on a iOS device then we store it on the server and an android user needs to play it, are we able to play it on android using MediaPlayer ANE?

**Comment by marchbold** [comment]
I think if you use the native media player you should be able to playback on both platforms, but I haven't tried this myself.

**Comment by justAnotherprogramWriter** [comment]
Hi, does MediaPlayer ANE have a trial version?

**Comment by marchbold** [comment]
Unfortunately we are changing over our license system so don't currently have the ability to give out trials.

**Comment by marchbold** [comment]
If you have any questions or concerns feel free to ask our team at airnativeextensions@distriqt.com

**Comment by justAnotherprogramWriter** [comment]
O. Okay. Thanks.

**Comment by mrwizzer** [comment]
Any updates? Need to know if this works on iOS yet.

**Comment by marchbold** [comment]
This ANE is free and not part of our support program so we will only update it in our spare time. Unfortunately we've not had any recently. If you wish to sponsor the development please contact us at the email above.

**Comment by mrwizzer** [comment]
So am I correct in assuming it does not support iOS at this time?  It looked like you guys were pursuing a version that worked with iOS, but perhaps not?

**Comment by marchbold** [comment]
We were working on it, but other priorities came up.
