### ISSUE TITLE
Unable to Play in iOS

### ISSUE THREAD

**Issue by speego76** [distriqt/ANE-AudioRecorder#10]
Hi @marchbold ,

I did place everything as the docs:
- Latest AIR
- Latest Extension
- Latest IOS

The application requires authorization correctly, records and save. I can trace the file, see all the action but unable to hear when play back.

There are no errors, everything looks correctly flowing, any advise what else can check?

```
file = File.applicationStorageDirectory.resolvePath("recording.m4a");
var options: AudioRecorderOptions = new AudioRecorderOptions();
options.filename = file.nativePath;
options.audioEncoding = AudioEncoder.AAC;
AudioRecorder.service.start(options);

playAudio.addEventListener(MouseEvent.CLICK, fplayAudio);
function fplayAudio(e: MouseEvent): void {
	trace("play audio");
	playRecording(file);
	removeEventListener(MouseEvent.CLICK, fplayAudio);
}

//////////
function playRecording(file:File): void {
	{		
		if (file) {
			trace("file exist");
			if (_nc == null) {
				_nc = new NetConnection();
				_nc.connect(null);
			}
			_ns = new NetStream(_nc);
			_ns.client = new Object();
			_ns.play( "file://"+ file.nativePath );
			trace('nativePath: ' + file.nativePath);
		} else {
			trace("ERROR: file doesn't exist");
		}
	}
}
```

TRACING////////
Record Audio
check auth
Record Audio
Auth in place, moving forward
audiorecorder:start
audiorecorder:progress
audiorecorder:progress
audiorecorder:progress
audiorecorder:progress
audiorecorder:progress
audiorecorder:progress
audiorecorder:progress
audiorecorder:progress
audiorecorder:progress
audiorecorder:progress
stopped audio
audiorecorder:complete
play audio
file exist
nativePath: /var/mobile/Containers/Data/Application/016600D6-A440-446B-A9D3-3FDE9DCF2D8F/Library/Application Support/xxx.xxx.xxx/Local Store/recording.m4a
Debug session terminated.
```

**Comment by marchbold** [comment]
Could you post the device logs from the device? https://docs.airnativeextensions.com/docs/tutorials/device-logs

What version of iOS have you encountered this issue on?

**Comment by speego76** [comment]
Hi Michael,

I am trouble having the logs for the IOS, the Windows Tools are not getting those as before, the iOS is 15.6.1

**Comment by marchbold** [comment]
I haven't tried to get the logs on Windows in a long time sorry so not sure what to suggest. Do you have access to a macOS machine at all?

**Comment by speego76** [comment]
Will put this to rest for now, have to focus in other items, closing for now.
