### ISSUE TITLE
ane audio recorder installation problems with apm

### ISSUE THREAD

**Issue by josquinet** [distriqt/ANE-AudioRecorder#12]
good morning. when in the terminal I put 

apm generate app-descriptor src/MyApp-app.xml

to modify my descriptor file I get back:

Android package name: air.com.my.recorder_voice.
⣾ Android manifest merging.
RunConfig::ERROR: Failed to find bin\java.exe
E::RunConfig::Error #2037
E::ProcessQueue::Failed to find 'bin\java.exe' in JAVA_HOME=null. Point JAVA_HOME to your java installation.
generate/app-descriptor :: Failed to find 'bin\java.exe' in JAVA_HOME=null. Point JAVA_HOME to your java installation.

the problem may be that i have modified the sdk by changing the adt file (to create the aab file) and there i have put that JAVA_HOME points to an android folder. i don't know if this will affect the installation of java. if this will affect the installation of the ANE in terms of modifying my descriptor file.

##### Environment 

- AIR SDK version: 50.2.4.1
- Device OS: WIN 10 Pro
- Device version: 22H2
- Development IDE: Animate
- Development OS: app for android

**Comment by josquinet** [comment]
I have solved it. I found my java.exe file and through the console I entered the JAVA_HOME path to that file and it generated the manifest file. Thank you very much.

**Comment by marchbold** [comment]
Glad to hear you resolved this one! 👍
