### ISSUE TITLE
Complete event not being triggered.

### ISSUE THREAD

**Issue by justAnotherprogramWriter** [distriqt/ANE-AudioRecorder#3]
Expected behaviour:
AudioRecorderEvent.COMPLETE to be triggered and play recorded sound.

Actual behaviour:
AudioRecorderEvent.COMPLETE not triggered. Trace in the complete handler not traced out.

```as3
private function audioRecorder_completeHandler( event:AudioRecorderEvent ):void
		{
			var file:File = File.applicationStorageDirectory.resolvePath("recording.m4a");
			
			if (_nc == null)
			{
				_nc = new NetConnection();
				_nc.connect(null);
			}
			_ns = new NetStream( _nc );
			_ns.client = new Object();
			trace("playing the sound?");
			_ns.play( "file://"+file.nativePath );
		}
```

I also got this error when I tried to trace out:

Error #3500: The extension context does not have a method with the name isSupported.

Environment:
- AIR SDK version: 29
- Device OS: Android
- OS Version: Android 8

Hi, I am trying out this ane for my project. I need to be able to play music and record it together with user's voice. Is it possible with this ane? I am trying to try this ane first with default example, but the complete even is not even triggered. Can you please advice?

**Comment by marchbold** [comment]
The complete event should be triggered when you call `stop()`. 

However that error would indicate that something is wrong with the packaging of the extension. There are a few ANE dependencies, make sure you have added them all:

https://github.com/distriqt/ANE-AudioRecorder/wiki/i.Add-the-Extension  

Missing those ANEs can cause that error message.

**Comment by justAnotherprogramWriter** [comment]
It is `AudioRecorder.service.stop();` right? 

Was it because of 

> Error #3500: The extension context does not have a method with the name isSupported. 

that the stop function is not working?

I tried to include all the dependencies, but it conflicted with my existing dependencies with the following errors:

Error occurred while packaging the application:


aapt tool failed:

..\android.support.v7.appcompat-res\values\values.xml:71: error: Attribute "navigationMode" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:73: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:78: error: Attribute "displayOptions" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:79: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:94: error: Attribute "tickMarkTintMode" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:109: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:110: error: Attribute "actionBarSize" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:129: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:115: error: Attribute "buttonTintMode" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:135: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:128: error: Attribute "showDividers" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:149: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:137: error: Attribute "showAsAction" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:173: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:155: error: Attribute "thumbTintMode" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:204: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:168: error: Attribute "trackTintMode" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:217: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:183: error: Attribute "buttonGravity" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:232: Original attribute defined here.
..\android.support.v7.appcompat-res\values\values.xml:190: error: Attribute "backgroundTintMode" already defined with incompatible format.
..\appcompat-v7-27.0.2-res\values\values.xml:239: Original attribute defined here.

If I am to remove my existing dependencies, my existing features of the project will not work.

**Comment by justAnotherprogramWriter** [comment]
It is `AudioRecorder.service.stop();` right? 

Was it because of 

> Error #3500: The extension context does not have a method with the name isSupported. 

that the stop function is not working?

I tried to include all the dependencies:

> com.distriqt.androidsupport.V4.ane
> com.distriqt.Core.ane

, but it conflicted with my existing dependencies with the following errors:

> Error occurred while packaging the application:
>  
> dx tool failed:
> UNEXPECTED TOP-LEVEL EXCEPTION:
> java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResultCallback;
> 	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
> 	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
> 	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
> 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
> 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
> 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
> 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
> 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
> 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
> 	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
> 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
> 	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
> 	at com.android.dx.command.dexer.Main.run(Main.java:245)
> 	at com.android.dx.command.dexer.Main.main(Main.java:215)
> 	at com.android.dx.command.Main.main(Main.java:106)
> 
> UNEXPECTED TOP-LEVEL EXCEPTION:
> java.lang.IllegalArgumentException: already added: Landroid/support/v4/graphics/BitmapCompat;
> 	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
> 	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
> 	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
> 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
> 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
> 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
> 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
> 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
> 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
> 	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
> 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
> 	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
> 	at com.android.dx.command.dexer.Main.run(Main.java:245)
> 	at com.android.dx.command.dexer.Main.main(Main.java:215)
> 	at com.android.dx.command.Main.main(Main.java:106)
> 
> UNEXPECTED TOP-LEVEL EXCEPTION:
> java.lang.IllegalArgumentException: already added: Landroid/support/v4/widget/ViewDragHelper$Callback;
> 	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
> 	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
> 	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
> 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
> 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
> 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
> 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
> 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
> 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
> 	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
> 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
> 	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
> 	at com.android.dx.command.dexer.Main.run(Main.java:245)
> 	at com.android.dx.command.dexer.Main.main(Main.java:215)
> 	at com.android.dx.command.Main.main(Main.java:106)
> 
> UNEXPECTED TOP-LEVEL EXCEPTION:
> java.lang.IllegalArgumentException: already added: Landroid/support/v4/graphics/ColorUtils;
> 	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
> 	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
> 	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
> 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
> 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
> 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
> 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
> 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
> 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
> 	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
> 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
> 	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
> 	at com.android.dx.command.dexer.Main.run(Main.java:245)
> 	at com.android.dx.command.dexer.Main.main(Main.java:215)
> 	at com.android.dx.command.Main.main(Main.java:106)
> 
> UNEXPECTED TOP-LEVEL EXCEPTION:
> java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/FragmentManagerImpl$OpGenerator;
> 	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
> 	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
> 	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
> 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
> 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
> 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
> 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
> 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
> 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
> 	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
> 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
> 	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
> 	at com.android.dx.command.dexer.Main.run(Main.java:245)
> 	at com.android.dx.command.dexer.Main.main(Main.java:215)
> 	at com.android.dx.command.Main.main(Main.java:106)
> 
> UNEXPECTED TOP-LEVEL EXCEPTION:
> java.lang.IllegalArgumentException: already added: Landroid/support/v4/media/MediaBrowserServiceCompat$ServiceBinderImpl$2;
> 	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
> 	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
> 	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
> 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
> 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
> 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
> 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
> 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
> 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
> 	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
> 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
> 	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
> 	at com.android.dx.command.dexer.Main.run(Main.java:245)
> 	at com.android.dx.command.dexer.Main.main(Main.java:215)
> 	at com.android.dx.command.Main.main(Main.java:106)
> 
> UNEXPECTED TOP-LEVEL EXCEPTION:
> java.lang.IllegalArgumentException: already added: Landroid/support/v4/BuildConfig;
> 	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
> 	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
> 	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
> 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
> 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
> 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
> 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
> 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
> 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
> 	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
> 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
> 	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
> 	at com.android.dx.command.dexer.Main.run(Main.java:245)
> 	at com.android.dx.command.dexer.Main.main(Main.java:215)
> 	at com.android.dx.command.Main.main(Main.java:106)
> 7 errors; aborting
> 

If I am to remove my existing dependencies, my existing features of the project will not work. Should I include the following dependencies too?:

> com.distriqt.androidsupport.AppCompatV7.ane
> com.distriqt.androidsupport.CardViewV7.ane
> com.distriqt.androidsupport.CustomTabs.ane
> com.distriqt.androidsupport.Design.ane
> com.distriqt.androidsupport.RecycleViewV7.ane

Because when I did include those 5 dependencies, I am getting more conflicts with my existing anes too.

**Comment by marchbold** [comment]
We can't guarantee that it will work with older versions of the Android support libs so we recommend using ours where possible, however you can attempt to use another version if you wish.

As a minimum you need to include our Core ANE. If you are encountering a conflict with another ANE including the `com.adobe.air.ActivityResultCallback` (the first conflict listed above) then remove `com.distriqt.Core.ane` and use the version without this included `com.distriqt.Core.noair.ane`. Our extensions will then use the definition in your other ANE.

**Comment by justAnotherprogramWriter** [comment]
Managed to get it working with noair.ane. Thanks a lot! You are a life-saver.

**Comment by marchbold** [comment]
Nice work, good to hear!
