### ISSUE TITLE
Recorded audio can only be loaded as a Netstream?

### ISSUE THREAD

**Issue by justAnotherprogramWriter** [distriqt/ANE-AudioRecorder#4]
##### Expected behaviour
Using AS3 default sound loader(or greensock LoaderMax) to load the recorded audio after it is saved in applicationStorageDirectory. Then play the sound with a sound channel.

##### Actual behaviour
Sound loader triggers no errors, in fact it triggered to completed event, which means it is successfully loaded. However, when played, it seemed that the sound ended immediately as sound complete event is triggered. Playing it with Netstream, does produce the recorded audio

##### Environment 

- AIR SDK version: 29
- Device OS: Android and IOS
- Device version: Android 8 and IOS 9

Please advice.

**Comment by marchbold** [comment]
I'm not exactly sure how the LoaderMax loads sounds, it's been a while since I've used that. My guess is that the format of the files is not supported.

**Comment by justAnotherprogramWriter** [comment]
Is mp3 supported? I realized that LoaderMax and the default AS3 Sound loader takes in mp3.

**Comment by marchbold** [comment]
It records to the native audio recording format, which defaults to mp4/aac. Neither platforms support recording to mp3. 

You'll need to convert to mp3 after recording if you need mp3.

**Comment by justAnotherprogramWriter** [comment]
I see... Thanks for your reply. I will look for an ane that can convert m4a to mp3.
